Question 1:
Retrieve the total number of rentals made in the Sakila database.
Hint: Use the COUNT() function.



Question 2:
Find the average rental duration (in days) of movies rented from the Sakila database.

Hint: Utilize the AVG() function.
Also ensures that only completed rentals should be considered in the average calculation.



Question 3:
Display the first name and last name of customers in uppercase.
Hint: Use the UPPER () function.



Question 4:
Extract the month from the rental date and display it alongside the rental ID.
Hint: Employ the MONTH() function.



Question 5:
Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
Hint: Use COUNT () in conjunction with GROUP BY.



Question 6:
Find the total revenue generated by each store.
Hint: Combine SUM() and GROUP BY.




Question 7:
Display the title of the movie, customer s first name, and last name who rented it.
Hint: Use JOIN between the film, inventory, rental, and customer tables.
GROUP BY:
Joins:





Question 8:
Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
Hint: Use JOIN between the film actor, film, and actor tables.




Question 9:
Determine the total number of rentals for each category of movies.
Hint: JOIN film_category, film, and rental tables, then use cOUNT () and GROUP BY.



Question 10:
Find the average rental rate of movies in each language.
Hint: JOIN film and language tables, then use AVG () and GROUP BY.



Question 11:
Retrieve the customer names along with the total amount they've spent on rentals.
Hint: JOIN customer, payment, and rental tables, then use SUM() and GROUP BY.



Question 12:
List the titles of movies rented by each customer in a particular city (e.g., 'London').
Hint: JOIN customer, address, city, rental, inventory, and film tables, then use GROUP BY.




Question 13:
Display the top 5 rented movies along with the number of times they've been rented.
Hint: JOIN film, inventory, and rental tables, then use cOUNT() and GROUP BY, and limit the results.




Question 14:
Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).
Hint: Use JOINS with rental, inventory, and customer tables and consider COUNT() and GROUP BY.











